apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-1
spec:
  replicas: {{ .Values.userService.replicas }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
      - name: user-service
        image: {{ .Values.userService.image.repository }}:{{ .Values.global.imageTag }}
        ports:
        - containerPort: {{ .Values.userService.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-2
spec:
  replicas: {{ .Values.productService.replicas }}
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
      - name: product-service
        image: {{ .Values.productService.image.repository }}:{{ .Values.global.imageTag }}
        ports:
        - containerPort: {{ .Values.productService.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-3
spec:
  replicas: {{ .Values.orderService.replicas }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
      - name: order-service
        image: {{ .Values.orderService.image.repository }}:{{ .Values.global.imageTag }}
        ports:
        - containerPort: {{ .Values.orderService.port }}
